### ISSUE TITLE
Beginner Website

### ISSUE THREAD

**Issue by cenkberry** [cenkberry/Hanedarcicek#1]
I waiting your advises for my site.
Thank you....

**Comment by StefanTenev** [comment]
Hey, I assume that you are asking for ideas for your website? As a beginner, it would be fairly straightforward to build a website to document something, such as a personal portfolio, or a page such a wiki of someone or something.

**Comment by cenkberry** [comment]
@StefanTenev
Hello, nice to meet you.
You can use this repository to improve yourself and if you will have questions you can ask me.
I want to reply.

See you..

**Comment by StefanTenev** [comment]
> @StefanTenev Hello, nice to meet you. You can use this repository to improve yourself and if you will have questions you can ask me. I want to reply.
> 
> See you..

Oh...understandable...sorry for me reading it wrong ;D
